# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG Minia 2018"
email: "gdgminia@gmail.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "https://gdgminia.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "gdgminia.github.io"
siteVerification: ""

# Organizer Info
organizerName: "GDG Minia"
organizerAlternateName: "Google Developer Group Minia"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gdgminia@gmail.com"
organizerLogo: "/img/seo/GDG_Minia.png"
organizerLink: "http://gdgminia.com/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, minia"
twitterAccount: "@gdgminia"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "#"
c4sponsorsUrl: "#"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
= - {permalink: "/team/", text: "Team"}
bottomNavigationLinks:
 - {link: "#", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "#", text: "Become a speaker"}

# Hero Block
heroImage: "minia.jpg"
heroTitle: "GDG Minia <typeout> 2018"
eventDate: "Nobember - December, 2018"
typeoutTextValues: '"", "FCI", "Minia", "Egypt", "Minia"'
typeoutFallback: "Season"
heroButtons:
 - {link: "#", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in Minia carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }


# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: "from Minia and beyond"}


# Rockstar Speakers Block
rockstarSpeakersImage: "hazem.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Our Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Faculty of computers & Information"
eventLocationLink: "#"
eventStreetAddress: "Minia University"
eventAddressLocality: "Minia"
eventAddressLocalityRegion: "Egypt"
eventPostalCode: "79000"
eventAddressCountry: "Egypt"
eventStartTime: "2018-12-01T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-12-01T17:00"
eventPlaceCoordinates: "28.1232747,30.7325713"
mapCenterCoordinates: "28.1232747,30.7325713"
mapMobileCenterCoordinates: "28.1232747,30.7325713"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "gdgminia"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "#"
subscribeInfo: "Registration will be open around end of November. Number of tickets are limited. Stay tuned!"


# Footer
socialLinks:
 - {link: "https://facebook.com/GDG.Minia", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgminia.com", text: "GDGMinia.com"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gdgminia@gmail.com", text: "mailto:gdgminia@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}


# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."